### ISSUE TITLE
Need Dataset

### ISSUE THREAD

**Issue by HamzaAmeerHussain** [hairav/PPSGen#1]
please share dataset downloading link that you have used in this project.

**Comment by hairav** [comment]
I've mailed you the dataset, and the script that we used to procure it.
Kindly get back to us if you manage to add more pairs to the datasets.

**Comment by HamzaAmeerHussain** [comment]
Thank you so much brother.

**Comment by MorenoLaQuatra** [comment]
Could you please share it also with me?

**Comment by hairav** [comment]
@MorenoLaQuatra can you share your email?

**Comment by MorenoLaQuatra** [comment]
I just sent you an email. Thank you very much.

**Comment by yuanzilin** [comment]
> please share dataset downloading link that you have used in this project.



> Thank you so much brother.

hello, can you share the dataset with me？here is my email：1799926597@qq.com，thank you very much!
