### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by MorenoLaQuatra** [hairav/PPSGen#2]
Hi,

First of all thank you for sharing the code. It seems a very interesting approach. 

I would like to ask you if the data for the project are available and you could share it.

Thank you.

**Comment by yuanzilin** [comment]
> Hi,
> 
> First of all thank you for sharing the code. It seems a very interesting approach.
> 
> I would like to ask you if the data for the project are available and you could share it.
> 
> Thank you.

hello! could you please share the dataset with me? here is my email：1799926597@qq.com，
thank you very much!
