### ISSUE TITLE
Hello, could you pls share the PPSGen dataset with me? thx!

### ISSUE THREAD

**Issue by yuanzilin** [hairav/PPSGen#3]

**Comment by yuanzilin** [comment]
here is my email：1799926597@qq.com

**Comment by Furankyyy** [comment]
Same here! It would be great if you could share the dataset: furankyyy@yahoo.com

**Comment by yuanzilin** [comment]
anyone who need the dataset could share me the email, i will send you.

the dataset is crawl by Keshav hairav
